// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE_tBidEQEx7vM3pawEHsSJ9DIWvpvOOY',
    appId: '1:1041105419133:web:c59eeb25c5e9af88856a14',
    messagingSenderId: '1041105419133',
    projectId: 'gdsc-metu-social-media-app',
    authDomain: 'gdsc-metu-social-media-app.firebaseapp.com',
    storageBucket: 'gdsc-metu-social-media-app.appspot.com',
    measurementId: 'G-DYKHYHBC63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUuEgsrvmglyh_tWKrLI3O4YLikoxYwpo',
    appId: '1:1041105419133:android:8dd908382037144e856a14',
    messagingSenderId: '1041105419133',
    projectId: 'gdsc-metu-social-media-app',
    storageBucket: 'gdsc-metu-social-media-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUWbVosbceX9duFvzv81SvVHCPiHKVKzM',
    appId: '1:1041105419133:ios:5d4fc4c68e522053856a14',
    messagingSenderId: '1041105419133',
    projectId: 'gdsc-metu-social-media-app',
    storageBucket: 'gdsc-metu-social-media-app.appspot.com',
    iosBundleId: 'com.example.gdscSocialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUWbVosbceX9duFvzv81SvVHCPiHKVKzM',
    appId: '1:1041105419133:ios:0a67abe4ee557c5d856a14',
    messagingSenderId: '1041105419133',
    projectId: 'gdsc-metu-social-media-app',
    storageBucket: 'gdsc-metu-social-media-app.appspot.com',
    iosBundleId: 'com.example.gdscSocialMedia.RunnerTests',
  );
}
